check-time: "20:00"  # 格式为 HH:mm
check-schedule:
type: 'weekly' # 选项： 'daily', 'weekly', 'monthly'
days-of-week: [1, 3, 5] # 周一, 周三, 周五 (1 = 周六, 7 = 周日)
dates-of-month: [1] # 每月一号
deduct-based-on-time: true
# 下面两个选项仅在 deduct-based-on-time 为 true 时生效
inactive-days-to-deduct: 50  # 未上线扣款开始的天数
inactive-days-to-clear: 500  # 未上线清空余额的天数
# 按阶级扣税
tax-brackets:
  - threshold: 100000
    rate: 0.001
  - threshold: 1000000
    rate: 0.01
  - threshold: null  # null 表示无上限
    rate: 0.02

