name: EcoBalancer
version: '${project.version}'
main: org.cubexmc.ecobalancer.EcoBalancer
api-version: '1.20'
description: This plugin deducts money from inactive players' accounts using Vault.
author: angushushu
website: angushushu.com
depend: [Vault]
commands:
  help:
    description: Displays help information for EcoBalancer.
    usage: /help
  checkall:
    description: Clean or deduct all inactive players.
    usage: /checkall
  checkplayer:
    description: Clean or deduct a specific inactive player.
    usage: /checkplayer
permissions:
  ecobalancer.check:
    description: Allows use of checkall and checkplayer commands
    default: op