name: EcoBalancer
version: '${project.version}'
main: org.cubexmc.ecobalancer.EcoBalancer
api-version: '1.13'
description: This plugin deducts money from inactive players' accounts using Vault.
author: angushushu
website: angushushu.com
depend: [Vault]
softdepend: [Essentials]
folia-supported: true
commands:
  ecobal:
    description: Main command for EcoBalancer plugin.
    usage: /ecobal <subcommand> [arguments]
    aliases: [eb]
    permission: ecobalancer.command.ecobal
permissions:
  ecobalancer.command.ecobal:
    description: Allows use of all EcoBalancer commands
    default: op
    children:
      ecobalancer.command.checkall: true
      ecobalancer.command.checkplayer: true
      ecobalancer.command.stats: true
      ecobalancer.command.interval: true
      ecobalancer.command.perc: true
      ecobalancer.command.reload: true
      ecobalancer.command.checkrecords: true
      ecobalancer.command.checkrecord: true
      ecobalancer.command.restore: true
  ecobalancer.command.checkall:
    description: Allows use of /ecobal checkall command
    default: op
  ecobalancer.command.checkplayer:
    description: Allows use of /ecobal checkplayer command
    default: op
  ecobalancer.command.stats:
    description: Allows use of /ecobal stats command
    default: op
  ecobalancer.command.interval:
    description: Allows use of /ecobal interval command
    default: op
  ecobalancer.command.perc:
    description: Allows use of /ecobal perc command
    default: op
  ecobalancer.command.reload:
    description: Allows use of /ecobal reload command
    default: op
  ecobalancer.command.checkrecords:
    description: Allows use of /ecobal checkrecords command
    default: op
  ecobalancer.command.checkrecord:
    description: Allows use of /ecobal checkrecord command
    default: op
  ecobalancer.command.restore:
    description: Allows use of /ecobal restore command
    default: op
  ecobalancer.*:
    description: Grants all EcoBalancer permissions
    default: op
    children:
      ecobalancer.command.ecobal: true