check-time: "20:00"  # 格式为 HH:mm # Time format is HH:mm
check-schedule:
type: 'weekly' # 选项: 'daily', 'weekly', 'monthly' # Options: 'daily', 'weekly', 'monthly'
days-of-week: [1, 3, 5] # 周一, 周三, 周五 (6 = 周六, 7 = 周日) # Monday, Wednesday, Friday (6 = Saturday, 7 = Sunday)
dates-of-month: [1] # 每月一号 # 1st day of each month
deduct-based-on-time: true
# 下面两个选项仅在 deduct-based-on-time 为 true 时生效 # The following two options only take effect when deduct-based-on-time is true
inactive-days-to-deduct: 50  # 未上线扣款开始的天数 # Days inactive before starting deductions
inactive-days-to-clear: 500 # 未上线清空余额的天数 # Days inactive before clearing balance
# 按阶级扣税 # Tax brackets for deductions
tax-brackets:
  - threshold: 100000
    rate: 0.001 # 税率 # Tax rate
  - threshold: 1000000
    rate: 0.01 # 税率 # Tax rate
  - threshold: null # 无上限 # No limit
    rate: 0.02 # 税率 # Tax rate
tax-account: true # 是否使用税金账户 # Whether to use tax account
tax-account-name: 'tax' # 税金账户名称 # Tax account name