name: EcoBalancer
version: '1.0-SNAPSHOT'
main: org.cubexmc.ecobalancer.EcoBalancer
api-version: '1.13'
description: This plugin deducts money from inactive players' accounts using Vault.
author: angushushu
website: angushushu.com
depend: [Vault]
softdepend: [Essentials]
commands:
  checkall:
    description: Clean or deduct all inactive players.
    usage: /checkall
  checkplayer:
    description: Clean or deduct a specific inactive player.
    usage: /checkplayer
  ecobal:
    description: Utility command for EcoBalancer.
    usage: /ecobal <command>
    permission: ecobalancer.admin
permissions:
  ecobalancer.admin:
    description: Allows use of commands
    default: op