name: EcoBalancer
version: '1.1.0'
main: org.cubexmc.ecobalancer.EcoBalancer
api-version: '1.13'
description: This plugin deducts money from inactive players' accounts using Vault.
author: angushushu
website: angushushu.com
depend: [Vault]
softdepend: [Essentials]
commands:
  checkall:
    description: Clean or deduct all inactive players.
    usage: /checkall
    permission: ecobalancer.admin
  checkplayer:
    description: Clean or deduct a specific inactive player.
    usage: /checkplayer
    permission: ecobalancer.admin
  ecobal:
    description: Utility command for EcoBalancer.
    usage: /ecobal <command>
    permission: ecobalancer.admin
  stats:
    description: Show descriptive statistics.
    usage: /stats <number of bars> [low] [up]
    permission: ecobalancer.admin
  interval:
    description: List players' balance in a specific interval.
    usage: /interval [alphabet|balance] [low] [up] [page]
    permission: ecobalancer.admin
  perc:
    description: Show percentile of players' balance.
    usage: /perc <balance> [low] [up]
    permission: ecobalancer.admin
  reload:
    description: Reload the configuration file.
    usage: /ecobal reload
    permission: ecobalancer.admin
  checkrecords:
    description: Show all operations.
    usage: /checkrecords [page]
    permission: ecobalancer.admin
  checkrecord:
    description: Show detail of a specific operation.
    usage: /checkrecord <operation_id> [deduction|alphabet] [page]
    permission: ecobalancer.admin
  restore:
    description: Restore a specific operation.
    usage: /restore <operation_id>
    permission: ecobalancer.admin
permissions:
  ecobalancer.admin:
    description: Allows use of commands
    default: op