name: EcoBalancer
version: '1.1.0'
main: org.cubexmc.ecobalancer.EcoBalancer
api-version: '1.13'
description: This plugin deducts money from inactive players' accounts using Vault.
author: angushushu
website: angushushu.com
depend: [Vault]
softdepend: [Essentials]
commands:
  checkall:
    description: Clean or deduct all inactive players.
    usage: /checkall
    aliases: [ca]
    permission: ecobalancer.command.checkall
  checkplayer:
    description: Clean or deduct a specific inactive player.
    usage: /checkplayer
    aliases: [cp]
    permission: ecobalancer.command.checkplayer
  ecobal:
    description: Utility command for EcoBalancer.
    usage: /ecobal <command>
    aliases: [eb]
    permission: ecobalancer.command.ecobal
  stats:
    description: Show descriptive statistics.
    usage: /stats <number of bars> [low] [up]
    aliases: [st]
    permission: ecobalancer.command.stats
  interval:
    description: List players' balance in a specific interval.
    usage: /interval [alphabet|balance] [low] [up] [page]
    aliases: [int]
    permission: ecobalancer.command.interval
  perc:
    description: Show percentile of players' balance.
    usage: /perc <balance> [low] [up]
    aliases: [pc]
    permission: ecobalancer.command.perc
  reload:
    description: Reload the configuration file.
    usage: /ecobal reload
    aliases: [rl]
    permission: ecobalancer.command.reload
  checkrecords:
    description: Show all operations.
    usage: /checkrecords [page]
    aliases: [cr]
    permission: ecobalancer.command.checkrecords
  checkrecord:
    description: Show detail of a specific operation.
    usage: /checkrecord <operation_id> [deduction|alphabet] [page]
    aliases: [cd]
    permission: ecobalancer.command.checkrecord
  restore:
    description: Restore a specific operation.
    usage: /restore <operation_id>
    aliases: [rs]
    permission: ecobalancer.command.restore
permissions:
  ecobalancer.command.checkall:
    description: Allows use of /checkall command
    default: op
  ecobalancer.command.checkplayer:
    description: Allows use of /checkplayer command
    default: op
  ecobalancer.command.ecobal:
    description: Allows use of /ecobal command
    default: op
  ecobalancer.command.stats:
    description: Allows use of /stats command
    default: op
  ecobalancer.command.interval:
    description: Allows use of /interval command
    default: op
  ecobalancer.command.perc:
    description: Allows use of /perc command
    default: op
  ecobalancer.command.reload:
    description: Allows use of /ecobal reload command
    default: op
  ecobalancer.command.checkrecords:
    description: Allows use of /checkrecords command
    default: op
  ecobalancer.command.checkrecord:
    description: Allows use of /checkrecord command
    default: op
  ecobalancer.command.restore:
    description: Allows use of /restore command
    default: op
  ecobalancer.*:
    description: Grants all EcoBalancer permissions
    default: op
    children:
      ecobalancer.command.checkall: true
      ecobalancer.command.checkplayer: true
      ecobalancer.command.ecobal: true
      ecobalancer.command.stats: true
      ecobalancer.command.interval: true
      ecobalancer.command.perc: true
      ecobalancer.command.reload: true
      ecobalancer.command.checkrecords: true
      ecobalancer.command.checkrecord: true
      ecobalancer.command.restore: true