package org.cubexmc.ecobalancer.tax

enum class TaxDecisionResult {
    TAXED,
    EXEMPT,
    INSUFFICIENT_BALANCE_SKIPPED,
    DRAINED_TO_ZERO,
    NEGATIVE_BALANCE_FIXED,
    ZERO_DEDUCTION,
    SKIPPED_ONLINE,
    SKIPPED_INACTIVE_DAYS,
    SKIPPED_TAX_ACCOUNT,
    SKIPPED_NO_ACCOUNT,
    CLEARED,
}
